server {
    listen 5173;
    server_name localhost;
    port_in_redirect off;

    location ~* ^/assets/passengers/(.*)$ {
        rewrite ^/assets/passengers/(.*)$ /assets/$1 last;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
