server {
    listen 5173;
    server_name localhost;
    port_in_redirect off;

    location ~* ^/assets/passengers/(.*)$ {
        rewrite ^/assets/passengers/(.*)$ /assets/$1 last;
    }

    # Жестко кэшируем все картинки, шрифты и звуки на 30 дней
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|mp3|wav|ogg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, max-age=2592000, immutable";
        access_log off;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
