INITIAL_SEED_USERS = [
    {
        "id": "u-elena-01",
        "username": "Елена Васильева",
        "gender": "f",
        "role": "Шеф поездной бригады",
        "badge": "ВСМ-1 • Премиум",
        "shifts_count": 32,
        "service_psychology": 98,
        "safety_tech": 100,
        "routine_discipline": 95,
        "first_aid": 90,
        "loyalty_score": 98,
        "incidents_resolved": 48,
        "correct_decisions": 46,
        "streak_days": 7,
    },
    {
        "id": "u-senior-01",
        "username": "Алексей Смирнов",
        "gender": "m",
        "role": "Старший проводник",
        "badge": "ВСМ-1 • Бизнес-класс",
        "shifts_count": 14,
        "service_psychology": 85,
        "safety_tech": 100,
        "routine_discipline": 65,
        "first_aid": 40,
        "loyalty_score": 85,
        "incidents_resolved": 22,
        "correct_decisions": 18,
        "streak_days": 4,
    },
    {
        "id": "u-anna-04",
        "username": "Анна Родионова",
        "gender": "f",
        "role": "Старший проводник",
        "badge": "ВСМ-1 • Бизнес-класс",
        "shifts_count": 12,
        "service_psychology": 88,
        "safety_tech": 92,
        "routine_discipline": 80,
        "first_aid": 55,
        "loyalty_score": 86,
        "incidents_resolved": 19,
        "correct_decisions": 16,
        "streak_days": 5,
    },
    {
        "id": "u-trainee-02",
        "username": "Дмитрий Волков",
        "gender": "m",
        "role": "Проводник-стажер",
        "badge": "ВСМ-1 • Стажер",
        "shifts_count": 2,
        "service_psychology": 45,
        "safety_tech": 50,
        "routine_discipline": 40,
        "first_aid": 35,
        "loyalty_score": 62,
        "incidents_resolved": 4,
        "correct_decisions": 2,
        "streak_days": 1,
    },
    {
        "id": "u-maria-05",
        "username": "Мария Соколова",
        "gender": "f",
        "role": "Проводник-стажер",
        "badge": "ВСМ-1 • Стажер",
        "shifts_count": 3,
        "service_psychology": 55,
        "safety_tech": 60,
        "routine_discipline": 50,
        "first_aid": 40,
        "loyalty_score": 68,
        "incidents_resolved": 5,
        "correct_decisions": 4,
        "streak_days": 2,
    },
]

ACHIEVEMENTS_CATALOG = {
    "first_trip": {
        "title": "Первый рейс ВСМ",
        "description": "Успешно начать и пройти смену на высокоскоростной магистрали",
        "icon": "🚄",
    },
    "safety_first": {
        "title": "Страж безопасности",
        "description": "Безупречно пресечь нарушение пожарной или транспортной безопасности",
        "icon": "🛡️",
    },
    "med_hero": {
        "title": "Скорая помощь 400 км/ч",
        "description": "Грамотно оказать помощь пассажиру при медицинском инциденте",
        "icon": "🩺",
    },
    "sto_expert": {
        "title": "Знаток СТО РЖД",
        "description": "Принять 5 верных решений подряд строго по регламенту ВСМ",
        "icon": "📜",
    },
    "team_player": {
        "title": "Командная работа",
        "description": "Привлечь начальника поезда или пассажиров для решения сложной ситуации",
        "icon": "🤝",
    },
}
